### ISSUE TITLE
Can't monitor notifications

### ISSUE THREAD

**Issue by luaVolk** [dbusjs/node-dbus-next#41] opened 2019-10-25 03:12 UTC
Im trying to monitor notifications but it stops listening after the first notification.

```js
var dbus = require('dbus-next')
const bus = dbus.sessionBus();

bus.getProxyObject('org.freedesktop.DBus', '/org/freedesktop/DBus').then((obj) => {
  let monitor = obj.getInterface('org.freedesktop.DBus.Monitoring');

  monitor.BecomeMonitor([
    "type='signal',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
    "type='method_call',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
    "type='method_return',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
    "type='error',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'"
  ], 0);


  bus.on('message', (msg) => {
    console.log(msg);
  });

});
```

**Comment by acrisci** [comment] 2019-10-25 11:50
Yeah I can reproduce this. This should work.

**Comment by acrisci** [comment] 2019-10-25 13:02
Try with #42 which makes the example work and see if anything else goes wrong.

**Comment by acrisci** [comment] 2019-10-25 17:44
Ok I'll run some more tests on it and include it in the next release.

**Comment by acrisci** [comment] 2019-11-29 18:07
Fixed in #42.

**Closed by acrisci** 2019-11-29 18:07 UTC

**Comment by kunaljaydesai** [comment] 2020-06-10 00:19
this still seems to be happening to me (on latest release 0.8.2):

```
this.session_bus.getProxyObject('org.freedesktop.DBus', '/org/freedesktop/DBus').then((obj: any) => {
      let monitor = obj.getInterface('org.freedesktop.DBus.Monitoring');
      monitor.BecomeMonitor([
        "type='signal',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
        "type='method_call',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
        "type='method_return',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
        "type='error',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'"
      ], 0);
      this.session_bus.on('message', (msg) => {
        console.log(msg);
      });    
    });
```

I see the first notification but any notification after that shows up on the UI but not in the logs.

**Comment by acrisci** [comment] 2020-06-13 15:36
@kunaljaydesai Your script works for me.

**Comment by sergeylukin** [comment] 2022-09-16 13:19
> this still seems to be happening to me (on latest release 0.8.2):
> 
> ```
> this.session_bus = dbus.sessionBus();
> this.session_bus.getProxyObject('org.freedesktop.DBus', '/org/freedesktop/DBus').then((obj: any) => {
>       let monitor = obj.getInterface('org.freedesktop.DBus.Monitoring');
>       monitor.BecomeMonitor([
>         "type='signal',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
>         "type='method_call',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
>         "type='method_return',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
>         "type='error',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'"
>       ], 0);
>       this.session_bus.on('message', (msg) => {
>         console.log(msg);
>       });    
>     });
> ```
> 
> I see the first notification but any notification after that shows up on the UI but not in the logs.

Took me forever to figure it out. In short: use `bus.addMethodHandler(cb)` rather than `bus.on('message', cb)` when subscribing via `BecomeMonitor`, like so:

```
var session_bus = dbus.sessionBus();
session_bus.getProxyObject('org.freedesktop.DBus', '/org/freedesktop/DBus').then((obj: any) => {
      let monitor = obj.getInterface('org.freedesktop.DBus.Monitoring');
      monitor.BecomeMonitor([
        "type='signal',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
        "type='method_call',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",        
         "type='method_return',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'",
        "type='error',member='Notify',path='/org/freedesktop/Notifications',interface='org.freedesktop.Notifications'"
      ], 0);
      session_bus.addMethodHandler((msg) => {
        console.log(msg);
        return true; // missing that little detail may turn your debugging into a nightmare, be aware
      });    
    });
```

Oh, and notice that `return true` in `addMethodHandler()`? Yeah, it's what keeps the emit chain in continuously working state - remove it and you will have just one event being triggered. Hope that makes sense :)

cc @acrisci
